CHANGES: Fix glitch that broke docutils/sphinx-issues
docutils 0.14
Sphinx 2.0.1
sphinx-issues 1.2.0

Exception occurred:
  File
  "~/.local/share/virtualenvs/tmuxp-UhdS5n5p/lib/python3.7/site-packages/docutils/nodes.py",
  line 93, in setup_child
      child.parent = self
      AttributeError: 'NoneType' object has no attribute 'parent'

Source:

1.0.0-rc1 <2016-05-25>
----------------------
- version jump 0.11.1 to 1.0
- :issue:`0`  tests moved to py.test framework
- :issue:`0`  `libtmux`_ core split into its own project

.. _libtmux: https://github.com/tmux-python/libtmux