chore(command_freeze): Fix odd type / cycling issue caused by import
See also:

tmuxp/cli/__init__.py:81:
    error: Cannot determine type of "command_freeze"