chore: Remove unused compat constant `console_encoding`
src/tmuxp/_compat.py:18: error: Item "None" of "TextIOWrapper | None" has no attribute "encoding"  [union-attr]