types(cli): Fix for missing literal
src/tmuxp/cli/__init__.py:172: error: Non-overlapping equality check (left operand type: Literal['ls'], right operand type: Literal['freeze'])  [comparison-overlap]